accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	login_view,
	logout_view,
	register_view,
	) 

urlpatterns = [
    url(r'^login/$', login_view, name= "login"),
    url(r'^logout/$', login_view, name= "logout"),
    url(r'^register/$', register_view, name= "register"),
    # url(r'^(?P<id>\d+)/delete/$', comment_delete, name = "delete"),
]

blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("accounts.urls", namespace= "accounts")),
    url(r'^comments/', include("comments.urls", namespace= "comments")),
    url(r'^posts/', include("posts.urls", namespace= "posts")),
    url(r'^api/posts/', include("posts.api.urls", namespace= "posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace= "comments-api")),
    # url(r'^/', include("posts.urls", namespace= "posts")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    PostCreateAPIView,
	PostListAPIView,
	PostDetailAPIView,
	PostUpdateAPIView,
	PostDeleteAPIView,
	) 

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name= "list"),
    url(r'^create/$', PostCreateAPIView.as_view(), name= "create"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name= "detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name= "update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name= "delete"),
    # url(r'^(?P<slug>[\w-]+)/$', post_detail, name= "detail"),
    # url(r'^$', post_list, name="list"),
    # url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name= "update"),
    # url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	) 

urlpatterns = [
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name= "detail"),
    url(r'^$', post_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name= "update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

comments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse

from django.db import models

#Pendiente del doble import 
# from posts.models import Post

class CommentManager(models.Manager):

	def all(self):
		qs = super(CommentManager, self).filter(parent=None)
		return qs


	def filter_by_instance(self, instance):
		content_type = ContentType.objects.get_for_model(instance.__class__)
		obj_id = instance.id
		qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
		return qs
# Create your models here.
class Comment(models.Model):
	parent = models.ForeignKey("self", null=True, blank=True)
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	# post 		= models.ForeignKey(Post)
	content 	= models.TextField()
	timestamp 	= models.DateTimeField(auto_now_add=True)

	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')

	objects = CommentManager()

	class Meta:
		ordering = ['-timestamp']

	def __unicode__(self):
		return self.user.username

	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse("comments:thread", kwargs={"id":self.id})

	def get_delete_url(self):
		return reverse("comments:delete", kwargs={"id":self.id})

	def children(self):
		return Comment.objects.filter(parent=self)

	@property
	def is_parent(self):
		if self.parent is not None:
			return False
		return True

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time
# Create your models here.

class PostManager(models.Manager):

	def active_posts(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	# filebase, extension = filename.split(".")
	return "%s/%s" %(instance.id, filename)

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field="width_field", height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	read_time = models.IntegerField(default=0)

	objects = PostManager()

	def __unicode__(self):
		return self.title


	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})
		# return "/posts/%s/" %(self.id)

	def get_markdown(self):
		content = self.content
		return mark_safe(markdown(content))

	class Meta:
		ordering = ["-timestamp", "-updated"]

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
	print instance

	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time = get_read_time(html_string)
		instance.read_time = read_time



pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
	SearchFilter,
	OrderingFilter,
	)


from .pagination import PostLimitOffsetPagination, PostPageNumberPagination


from rest_framework.generics import (
	CreateAPIView,
	DestroyAPIView,
	ListAPIView, 
	UpdateAPIView,
	RetrieveAPIView,
	RetrieveUpdateAPIView
	)

from rest_framework.permissions import (
	AllowAny,
	IsAuthenticated,
	IsAdminUser,
	IsAuthenticatedOrReadOnly,
	)

from posts.models import Post
from .serializers import PostCreateUpdateSerializer, PostListSerializer, PostDetailSerializer

from .permissions import IsOwnerOrReadOnly

class PostCreateAPIView(CreateAPIView):
	serializer_class = PostCreateUpdateSerializer
	permission_classes = [IsAuthenticated]
	def perform_create(self, serializer):
		serializer.save(user=self.request.user, title="my title")

class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	# http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview
	lookup_field = 'slug'


class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	# http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview
	lookup_field = 'slug'

	def perform_update(self, serializer):
		serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	# http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview
	lookup_field = 'slug'


class PostListAPIView(ListAPIView):
	# queryset = Post.objects.all()
	serializer_class = PostListSerializer
	filter_backends = [SearchFilter, OrderingFilter]
	search_fields = ['title', 'content', 'user__username']
	pagination_class = PostPageNumberPagination

	def get_queryset(self, *args, **kwargs):
		# queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
		queryset_list = Post.objects.all()
		q = self.request.GET.get('q')
		if q:
			queryset_list = queryset_list.filter(
				Q(title__icontains=q)|
				Q(content__icontains=q) |
				Q(user__username__icontains=q)
				).distinct()
		return queryset_list

posts/views.py
from urllib import quote_plus

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q

from .models import Post
from .forms import PostForm
from comments.models import Comment
from comments.forms import CommentForm
# Create your views here.

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		messages.success(request, "Successfully created")
		return HttpResponseRedirect(instance.get_absolute_url())
	if request.method=="POST":
		print request.POST
	context = {
		'form' : form
	}
	return render(request, "post_form.html", context)


def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.draft or instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)
	comments = instance.comments
	initial_data = {
		"content_type": instance.get_content_type,
		"object_id": instance.id
	}
	comment_form = CommentForm(request.POST or None, initial=initial_data)

	if comment_form.is_valid() and request.user.is_authenticated():
		print(comment_form.cleaned_data)
		c_type = comment_form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = comment_form.cleaned_data.get("object_id")
		content_data = comment_form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		new_comment, created = Comment.objects.get_or_create(
				user = request.user,
				content_type = content_type,
				object_id = obj_id,
				content = content_data,
				parent = parent_obj
			)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	context = {
		"title": "Detail",
		"post": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form": comment_form,
	}
	return render(request, "post_detail.html", context)


def post_list(request):
	qs_list = Post.objects.active_posts()
	if request.user.is_staff or request.user.is_superuser:
		qs_list = Post.objects.all()
	
	q = request.GET.get('q')
	if q:
		qs_list = qs_list.filter(
			Q(title__icontains=q)|
			Q(content__icontains=q) |
			Q(user__username__icontains=q)
			).distinct()

	paginator = Paginator(qs_list, 2) # Show 25 contacts per page

	
	page = request.GET.get('page')
	try:
		qs = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		qs = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		qs = paginator.page(paginator.num_pages)
	context = {
		"queryset": qs,
		"title": "List Page"
	}

	return render(request, "post_list.html", context)


def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Successfully created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"title": "Detail",
		"post": instance,
		"form": form
	}
	return render(request, "post_form.html", context)


def post_delete(request, id= None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, id=id)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block head_title%} Blog {% endblock head_title%}</title>

	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

	{% block headextra %} {% endblock %}
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.8&appId=108066706206323";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% include "messages_display.html"%}


<div class="container">
	<ol class="breadcrumb">
		<li><a href="{% url 'posts:list' %}">Home</a></li>
		{% block post_detail_link %}
			
		{% endblock %}
		{% if not request.user.is_authenticated %}
		<li class="pull-right"><a href="{% url 'accounts:register' %}">Register</a></li>
		<li class="pull-right"><a href="{% url 'accounts:login' %}">Login</a></li>
		{% else %}
		<li class="pull-right"><a href="{% url 'accounts:logout' %}">Logout</a></li>
		{% endif %}
	</ol>
	{% block content %}
	

	{% endblock content %}
	
	
</div>
<!-- Latest compiled and minified JavaScript -->

<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		$(".content-markdown").each(function(){
			var content = $(this).text().trim()
			console.log(content)
			var markedContent = marked(content)
			console.log(markedContent)
			$(this).html(markedContent)
		});

		$(".post-detail-item img").each(function(){
			$(this).addClass("img-responsive")
		});

		//preview-title
		var titleItem = $("#id_title");
		console.log(titleItem.val())
		$("#preview-title").text(titleItem.val());
		
		//preview-content

		
		// console.log(contentItem.val())
		// $("#preview-content").html(marked(contentItem.val()));
		

		function setContent(value){
			var markedContent = marked(value)
			$("#preview-content").html(markedContent)
			$("#preview-content img").each(function(){
				$(this).addClass("img-responsive")
			});
		}

		function setTitle(value){
			$("#preview-title").text(value);
		}

		var contentInput = $("#id_content");
		setContent(contentInput.val())
		contentInput.keyup(function(){
			var newContent = $(this).val()
			setContent(newContent)
		});

		titleItem.keyup(function(){
			var newContent = $(this).val()
			setTitle(newContent)
		});
		
		$(".comment-reply-btn").click(function(event){
			event.preventDefault();
			console.log($(this).parent().next());
			$(this).parent().next(".comment-reply").fadeToggle();
		});

	});
</script>
</body>
</html>

templates/comment_thread.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title%} Details {% endblock head_title%}

{% block content %}

{{object}}
	<div class="col-sm-6 col-sm-offset-3">
	

 
			
  				<p>{{comment.content}}</p>
  				<footer>via {{comment.user}} | {{comment.timestamp|timesince}} ago | {% if comment.children.count > 0%} {{comment.children.count}} Comments {% endif %} {% if request.user == comment.user %}<a href="{{comment.get_delete_url}}">Delete</a>{% endif %}</footer>
  				<hr>
  				<div>
		  			{% for child in comment.children %}
			  			<blockquote>
			  			<p>{{child.content}}</p>
			  			<footer>via {{child.user}} | {{child.timestamp|timesince}} ago | {% if request.user == comment.user %}<a href="{{child.get_delete_url}}">Delete</a>{% endif %}</footer>
			  			</blockquote>
		  			{% endfor %}
	  				
	  				{% if request.user.is_authenticated %}
		  			<form method="POST" action=""> {% csrf_token %}
						{{comment_form|crispy}}
					<input type="hidden" name="parent_id" value="{{comment.id}}">
					<input type="submit" name="" value="Replay" class="btn btn-primary">
					</form>
					{% else %}
					<p>Log in first</p>
					{% endif%}
				</div>
			
			<hr>
	

	</div>
	
{% endblock content %}

templates/confirm_delete.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title%} Details {% endblock head_title%}

{% block content %}


	<div class="col-sm-6 col-sm-offset-3">
  				<h1>Confirm Delete</h1>
		  			<form method="POST" action=""> {% csrf_token %}
					<p>Are you sure you want to delete  "{{object.content}}"?</p>
					<input type="submit" name="" value="Confirm" class="btn btn-warning">
					<a href="{{object.get_absolute_url}}" class="btn btn-default">Cancel</a>
					</form>
				</div>
			
		

	</div>
	
{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block headextra %} {{form.media}}{% endblock %}

{% block head_title%}Create {% endblock head_title%}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}} </h1>
	<form method="POST" action=""> {% csrf_token%}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" name="createPost" value="Log in">
	</form>
</div>
{% endblock content%}
	

templates/messages_display.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/post_detail.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% load urlify %}

{% block head_title%} Details {% endblock head_title%}

{% block post_detail_link %}
	<li><a href="{{post.get_absolute_url}}"> {{post.title}}</a></li>
{% endblock %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">
	{% if post.image %}
		<img src="{{post.image.url}}" class="img-responsive">
	{% endif%}
		
		<h1>{{title}} <small>{{post.publish}} {% if post.draft %} <span style="color:red;">Draft</span> {% endif %}</small></h1>
	{{post.title}}</br>
	<p>Read time : {{post.read_time}} minutes</p>
	<p>Author: {{post.user.username}}</p>
	<div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="box_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
	<!-- {{post.content|linebreaks}} -->
	<div class="row">
		<div class="col-sm-12 post-detail-item ">
			{{ post.get_markdown }}
		</div>
		<div class="col-sm-12">
			
		<div>
			<p class="lead">Comments</p>
			{% if request.user.is_authenticated %}
			<form method="POST" action=""> {% csrf_token %}
				{{comment_form|crispy}}
			<input type="submit" name="" value="Post comment" class="btn btn-primary">
			</form>
			{% else %}
				<p>You need to login to post a comment</p>
			{% endif %}
			{% for comment in comments %}
			<blockquote>
  				<p>{{comment.content}}</p>
  				<footer>via {{comment.user}} | {{comment.timestamp|timesince}} ago | {% if comment.children.count > 0%} {{comment.children.count}} Comments {% endif %} |<a class="comment-reply-btn" href="#">Replay</a> |<a href="{{comment.get_absolute_url}}">Thread</a></footer>

  				<div class="comment-reply" >
		  			{% for child in comment.children %}
			  			<blockquote>
			  			<p>{{child.content}}</p>
			  			<footer>via {{child.user}} | {{child.timestamp|timesince}} ago</footer>
			  			</blockquote>
		  			{% endfor %}
	  				{% if request.user.is_authenticated %}
		  			<form method="POST" action=""> {% csrf_token %}
						{{comment_form|crispy}}
					<input type="hidden" name="parent_id" value="{{comment.id}}">
					<input type="submit" name="" value="Replay" class="btn btn-primary">
					</form>
					{% else %}
						<p>Log in first</p>
					{% endif %}
				</div>
			</blockquote>
			<hr>
			{% endfor %}



			<!-- <p class="lead">Comments</p>
			{{comments}} -->
			<!-- {{ post.comment_set.all}} -->
		</div>

			<!-- <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div> -->
		</div>
	</div>
	
<!-- 	{{post.content|urlify}}
	<!-- {{request.build_absolute_uri}} -->
	<!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
Share on Facebook
</a>

<a href="https://twitter.com/home?status={{share_string}}%20{{request.build_absolute_uri}}">
Share on Twitter
</a> -->

<!-- <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'> -->

 

	</div>
	
{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block headextra %} {{form.media}}{% endblock %}

{% block head_title%}Create {% endblock head_title%}

{% block content%}
<div class="col-sm-6">
	<h1>
		Preview
	</h1>
	<div class="content-preview">
		<h3 id="preview-title"></h3>
		<p id="preview-content">
			
		</p>
	</div>
</div>
<div class="col-sm-6">
<h1>Form </h1>
	<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token%}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" name="createPost" value="Create Post">
	</form>
</div>
{% endblock content%}
	

templates/post_list.html
{% extends "base.html"%}
{% block head_title%} List {% endblock head_title%}</title>



	{% block content %}
		
		<div class="col-sm-6 col-sm-offset-3">
		<h1>{{title}}</h1>
		
      <form method="GET" action="" class="row"> 
      <div class="input-group col-sm-6">
         <input class="form-control" type="text" name="q" placeholder="Search somethin" value="{{request.GET.q}}">
         <span class="input-group-btn">
           <!-- <input class="btn btn-default" type="submit" value="Search Posts!" name=""> -->
           <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
         </span>
        
      </div>
    </form>
    
		{% for obj in queryset %}
			
			

<div class="row">

  <div class="col-sm-">
    <div class="thumbnail">
    	{% if obj.image %}
    	<img src="{{obj.image.url}}" class="img-responsive">
    	{% endif%}
      
      <div class="caption post-detail-item">
        <h3><a href="{% url 'posts:detail' slug=obj.slug %}">{{obj.title}}</a> <small>{{obj.timestamp|timesince}} ago</small></h3>
        <p>{{obj.user.username}}</p>
        <p class="post-detail-item" >{{obj.get_markdown|truncatechars_html:9}}</p>
        <p><a href="{% url 'posts:detail' slug=obj.slug %}" class="btn btn-primary" role="button">View Post</a> 
      </div>
    </div>
  </div>
<hr/>
  		<!-- {% cycle "" "<div class='col-sm-12'><hr/></div><div class='row'></div>" %} -->
  		</div>
		{% endfor %}
</div>

<div class="col-sm-6 col-sm-offset-3">
    <span class="step-links">
        {% if queryset.has_previous %}
            <a href="?page={{ queryset.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
            <a href="?page={{ queryset.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
	{% endblock content %}